language: node_js
node_js:
  - "6"
env:
  - NODE_ENV=ci
before_script:
  - openssl aes-256-cbc -K $encrypted_3354d85b94fc_key -iv $encrypted_3354d85b94fc_iv -in id_rsa.enc -out deploy_key -d
  - eval $(ssh-agent -s)
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config --global user.name "Travis CI"
  - git config --global user.email "$COMMIT_AUTHOR_EMAIL"
script:
  - ./node_modules/.bin/gulp build
  - if [[ $TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push ]]; then ./node_modules/.bin/gulp deploy; fi
